serial_test/src/lib.rs
serial_test_derive/src/lib.rs
serial_test_test/src/lib.rs

Fixes #5. There aren't any tests for this really, because the current state of proc macros makes this hard....

Skip ignore attribute, as it's already parsed out

---

Cargo.lock
README.md
serial_test/Cargo.toml
serial_test/src/lib.rs
serial_test_test/Cargo.toml
serial_test_test/src/lib.rs

This avoids the need to import two crates. Also update the documentation
to use the `serial_test` crate instead (the docs are still linked to
`serial_test_derive` since that is where the meat of the docs live for
the crate).
Fixes: #3

serial_test: re-export the `serial` macro

---

serial_test/src/lib.rs
serial_test_derive/src/lib.rs
serial_test_test/src/lib.rs

Allow tests with return values

---

serial_test/Cargo.toml

Hello, thanks for the great crate!
I was looking for this for a while since I have a subset of tests that must be run sequentially. I couldn't find anything searching on crates.io and gave up until I saw someone else using this crate. All this change does is add `sequential` as a keyword to hopefully guide other lost souls.

Add keywords to Cargo.toml

---

serial_test_derive/src/lib.rs

Remove extra braces around generated serial code to improve coverage

---

.github/workflows/ci.yml
serial_test/src/lib.rs

Mostly because of https://github.com/rust-lang/rust/issues/83310 but generally also useful

Permit beta/nightly clippy fails

---

README.md

This is a minor improvement to the documentation, clarifying that tests that are not marked as `serial` can run at any time (including in parallel to tests marked as `serial`). See #42.

Clarify docs for tests not marked as `serial`

---

.github/workflows/ci.yml
Cargo.lock
README.md
serial_test/Cargo.toml
serial_test_derive/Cargo.toml
serial_test_test/Cargo.toml

This also ups the version to 0.7, but doesn't release it yet. I'm _hoping_ to get parallel support out for that as well, but we'll see. Was going to be 1.49.0, but that broke [workspace feature selection](https://github.com/rust-lang/cargo/issues/5015) which makes testing harder so I've bumped to 1.51.0 for that.

Upgrade MSRV to 1.51 and upgrade packages that were blocked on it

---

Cargo.lock
serial_test/Cargo.toml
serial_test/src/code_lock.rs
serial_test/src/parallel_code_lock.rs
serial_test/src/rwlock.rs
serial_test/src/serial_code_lock.rs

Cope better with asserts inside parallel blocks

---

serial_test/Cargo.toml
serial_test/src/code_lock.rs

This change makes logging with the `log` crate a (default) feature but otherwise allows it, and the crate dependency, to be opted-out of by upstream consumers.

Make logging with log a default feature

---

serial_test/src/code_lock.rs
serial_test/src/lib.rs
serial_test_test/Cargo.toml

Following up on #63 not doing quite what I wanted it to, and supporting testing for #62

serial_test_test now switches off defaults for serial_test

---

.cargo/config.toml
.gitignore
serial_test/src/file_lock.rs
serial_test/src/serial_code_lock.rs
serial_test_test/src/lib.rs

* Remove and explicitly lint-out left over `println`'s
* Add a "assert in middle of test" test for file lock (which just works because [fslock implemented Drop](https://docs.rs/fslock/latest/fslock/struct.LockFile.html#impl-Drop))

Various tidyups for file lock

---

serial_test/Cargo.toml
serial_test/src/code_lock.rs
serial_test/src/lib.rs
serial_test/src/serial_code_lock.rs

This makes `timeout` a feature that is by default enabled, this preserves the API for backward compatibility. 
I also switched the Mutex of the MAX_WAIT to an RwLock, it's not on the critical path but it seemed sensible since it's mostly ever read and rarely written - it also removed two imports :)
I'll follow up with per test timeouts & eventual sequential start in further PRs

Intoduce timeout as a feature

---

Cargo.lock
serial_test/Cargo.toml
serial_test/src/code_lock.rs
serial_test/src/lib.rs
serial_test/src/parallel_code_lock.rs
serial_test/src/serial_code_lock.rs

Attempting to solve a problem spotted in https://github.com/palfrey/serial_test/pull/71. Mainly, that if there's any thread trying to add a new key into `LOCKS`, it'll fail while there's another one doing reads. [dashmap](https://docs.rs/dashmap/latest/dashmap/) gives us proper concurrent access, especially given we don't add a new entry to the hashmap once we've added the first lock, which I _think_ solves this.

Redo locks with dashmap

---

README.md
serial_test/Cargo.toml
serial_test/src/code_lock.rs
serial_test/src/lib.rs
serial_test/src/parallel_code_lock.rs
serial_test/src/parallel_file_lock.rs
serial_test/src/serial_code_lock.rs
serial_test/src/serial_file_lock.rs
serial_test/tests/tests.rs
serial_test_derive/src/lib.rs
serial_test_test/src/lib.rs

So this is still a draft, it adds the option to define a timeout as part of the serial test something along the lines of:
```rust
#[test]
#[serial(timeout = 600)]
fn test() -> {}
```
I've not added tests or documentation yet as I wanted to get feedback on if this approach is OK before putting in that work :)

Per test timeout

---

README.md
serial_test/Cargo.toml
serial_test/src/lib.rs
serial_test_derive/src/lib.rs

More clearly specifying the packages required for all the features, and unifying some of the timeout docs

Various docs fixes prior to 0.9

---

serial_test_derive/src/lib.rs

Closes #80
Allows test functions marked with `#[serial]` to be marked with `pub`.

Pass the function's visibilty to the generated function

---

README.md
serial_test/src/code_lock.rs
serial_test/src/lib.rs
serial_test/src/parallel_code_lock.rs
serial_test/src/parallel_file_lock.rs
serial_test/src/serial_code_lock.rs
serial_test/src/serial_file_lock.rs
serial_test/tests/tests.rs
serial_test_derive/src/lib.rs
serial_test_test/src/lib.rs

As noted in #79, `timeout_ms` is quite frankly confusing, doesn't do what people expect it to (set a timeout on a function) and also doesn't reliably do what I originally wanted it to do (detect test locks and timeout).
This PR therefore removes the whole thing.

Remove timeout_ms

---

.github/workflows/ci.yml
Cargo.lock
README.md
serial_test/Cargo.toml
serial_test/src/lib.rs
serial_test_derive/Cargo.toml
serial_test_derive/src/lib.rs
serial_test_derive/tests/broken/test_serial_async_before_wrapper.rs
serial_test_derive/tests/broken/test_serial_async_before_wrapper.stderr
serial_test_test/Cargo.toml
serial_test_test/src/lib.rs

As part of the investigations for https://github.com/palfrey/serial_test/issues/78, I found out that the async support was pretty broken. OTOH, this _mostly_ didn't matter, as most async test frameworks (certainly `tokio` and `actix`) both mess around with the function form enough in their macros so you could still write async test functions with them fine.
`wasm_bindgen_test` is less forgiving, and we now test with that explicitly.

Actually properly support async

---

serial_test_test/Cargo.toml

https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args was firing, but it's not relevant for our MSRV version

Set rust-version in test to fix clippy issue

---

serial_test_derive/src/lib.rs

Previously, we stripped them (see https://github.com/palfrey/serial_test/issues/5 / https://github.com/palfrey/serial_test/pull/10) but this seems to [cause issues with VS Code](https://github.com/palfrey/serial_test/issues/93) and I haven't yet found a case where this is actually needed now.

Stop stripping ignore/should_panic attributes

---

.github/workflows/ci.yml
Cargo.lock
README.md
serial_test/Cargo.toml
serial_test_derive/Cargo.toml
serial_test_test/Cargo.toml

Note that this bumps the MSRV all the way to 1.68.2. This will need a 2.0.0 release to go out. It's a much higher MSRV than is strictly needed for compilation, but aids my future maintenance burden by reducing the number of major releases I need to think about.

Upgrade to Syn 2

---

Cargo.lock
serial_test_derive/Cargo.toml

Workaround for https://github.com/dtolnay/proc-macro2/issues/356. Only occurs on nightly builds and fixable in individual projects by bumping proc-macro2 versions, so I won't be doing an explicit new release just for this.

Upgrade proc-macro2 to fix a nightly issue

---

Cargo.lock
README.md
serial_test/src/lib.rs
serial_test_derive/Cargo.toml
serial_test_derive/src/lib.rs
serial_test_test/src/lib.rs

Attributes at a mod-level

---

Cargo.lock
serial_test/Cargo.toml
serial_test/src/code_lock.rs
serial_test/src/parallel_code_lock.rs
serial_test/src/parallel_file_lock.rs
serial_test/src/rwlock.rs
serial_test/src/serial_code_lock.rs
serial_test/src/serial_file_lock.rs
serial_test_derive/Cargo.toml
serial_test_derive/src/lib.rs
serial_test_test/Cargo.toml
serial_test_test/src/lib.rs

Also add a _lot_ of debug (primarily around start of test, etc) which should all default to off
Mostly because of https://dev.to/acter/beware-of-the-dashmap-deadlock-lij but also wondering if this will solve the periodic test failures that I haven't previously been able to debug.

Replace dashmap with scc

---

serial_test_derive/src/lib.rs

This fixes things with any foo::test attribute (flagged in https://github.com/palfrey/serial_test/issues/103#issuecomment-2067688224)

Standard test attribute worked with mod, others didn't

---

serial_test_derive/src/lib.rs

The core problem was that `fn_setup` for non-async fns generated a function that could be parsed with `syn::parse2`, where as async ones generated two (the internal function and the wrapper). The code now still generates two, but the internal function is inside the wrapper, and so it's a single syntax item coming out.

Fix async test functions inside a serial mod block

---

Cargo.lock
serial_test/Cargo.toml
serial_test/src/parallel_code_lock.rs
serial_test/src/parallel_file_lock.rs

futures::executor::block_on() runs a future to completion in the current thread and there as nothing being spawned to a worker thread (e.g. tokio::spawn()).
Let's make it clear that nothing is running on the tokio runtime by removing it.
I'm not sure this is the right approach. Is there something here you explicitly want to have tested on the tokio runtime or perhaps even a different thread?

Stop using tokio in test which runs all futures sync

---

serial_test/src/code_lock.rs
serial_test/src/lib.rs
serial_test/src/rwlock.rs

I've recently had [this code added to rustls-tls-native](https://github.com/rustls/rustls-native-certs/pull/109):
```
/// Cargo, at least sometimes, sets SSL_CERT_FILE and SSL_CERT_DIR internally,
/// it uses OpenSSL. So, always unset both at the beginning of a test even if
/// the test doesn't use either.
///
/// # Safety
///
/// This is only safe if used together with `#[serial]` because calling
/// `[env::remove_var()]` is unsafe if another thread is running.
///
/// Note that `env::remove_var()` is scheduled to become unsafe in Rust
/// Edition 2024.
pub(crate) unsafe fn clear_env() {
env::remove_var("SSL_CERT_FILE");
env::remove_var("SSL_CERT_DIR");
}
```
`clear_env()` is called from various tests and it's really easy to forget `#[serial]`. This change will make it possible
to add an …

Add is_locked_serially() to check if we are in a #[serial] context

---

serial_test/Cargo.toml
serial_test_test/Cargo.toml

Fixes https://doc.rust-lang.org/edition-guide/rust-2024/cargo-table-key-names.html before we get there, as it's backwards compatible

default_features -> default-features

---

.github/workflows/ci.yml

Because it's installing cargo-all-features with `cargo install` and it's breaking (https://github.com/palfrey/serial_test/actions/runs/17364198516/job/49288431074) due to using packages from newer versions and so the 1.68.2 test breaks

Stop using cargo binstall
